"""accounting URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url
from django.contrib import admin
from accounting import views
from accounting import rebus_tier1_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.main_view),
    url(r'^/', views.main_view),
    url(r'^/images/$', RedirectView.as_view(url='/static/images/')),
    url(r'^report/resource_centers/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<report>[\w]+)/(?P<infra>[\w\s]+)/$', views.report_rc),
    url(r'^report/resource_centers/$', views.report_rc),
    url(r'^report/disciplines/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<infra>[\w\s]+)/(?P<disciplines>[\w\W\s;]+)/$', views.report_dis),
    url(r'^report/disciplines/$', views.report_dis),
    url(r'^wlcg/report/tier2/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.wlcg_report_tier2),
    url(r'^wlcg/report/tier2/$', views.wlcg_report_tier2),
    url(r'^wlcg/report/countries/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.wlcg_report_countries),
    url(r'^wlcg/report/countries/$', views.wlcg_report_countries),
    url(r'^report/interngi/(?P<query>[\w]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.report_interngi),
    url(r'^report/interngi/$', views.report_interngi),
    url(r'^report/vomet/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.report_vomet),
    url(r'^report/vomet/$', views.report_vomet),

    url(r'^disciplines/cloud/$', views.discipline_cloud_view),
    url(r'^disciplines/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/$', views.discipline_cloud_view),
    url(r'^disciplines/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.discipline_cloud_view),
    url(r'^disciplines/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.discipline_cloud_view),
    url(r'^disciplines/cloud/(?P<query>[\w]+)/$', views.discipline_cloud_view),
    url(r'^discipline/cloud/(?P<discipline>[^/]*?)/$', views.discipline_cloud_view),
    url(r'^discipline/cloud/(?P<discipline>[^/]*?)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/$', views.discipline_cloud_view),
    url(r'^discipline/cloud/(?P<discipline>[^/]*?)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.discipline_cloud_view),
    url(r'^discipline/cloud/(?P<discipline>[^/]*?)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.discipline_cloud_view),
    url(r'^discipline/cloud/(?P<discipline>[^/]*?)/(?P<query>[\w]+)/$', views.discipline_cloud_view),

    url(r'^disciplines/$', views.discipline_view),
    url(r'^disciplines/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/$', views.discipline_view),
    url(r'^disciplines/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.discipline_view),
    url(r'^disciplines/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.discipline_view),
    url(r'^disciplines/(?P<query>[\w]+)/$', views.discipline_view),
    url(r'^discipline/(?P<discipline>[^/]*?)/$', views.discipline_view),
    url(r'^discipline/(?P<discipline>[^/]*?)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/$', views.discipline_view),
    url(r'^discipline/(?P<discipline>[^/]*?)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.discipline_view),
    url(r'^discipline/(?P<discipline>[^/]*?)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.discipline_view),
    url(r'^discipline/(?P<discipline>[^/]*?)/(?P<query>[\w]+)/$', views.discipline_view),

    url(r'^tier1/cloud/node/(?P<node>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier1_cloud_node_view),
    url(r'^tier1/cloud/node/(?P<node>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.tier1_cloud_node_view),
    url(r'^tier1/cloud/node/(?P<node>[\w-]+)/$', views.tier1_cloud_node_view),
    url(r'^tier1/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier1_cloud_site_view),
    url(r'^tier1/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.tier1_cloud_site_view),
    url(r'^tier1/cloud/site/(?P<site>[\w-]+)/$', views.tier1_cloud_site_view),
    url(r'^tier1/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier1_cloud_view),
    url(r'^tier1/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.tier1_cloud_view),
    url(r'^tier1/cloud/$', views.tier1_cloud_view),
    url(r'^tier2/cloud/country/(?P<country>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier2_cloud_country_view),
    url(r'^tier2/cloud/country/(?P<country>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.tier2_cloud_country_view),
    url(r'^tier2/cloud/country/(?P<country>[\w\S-]+)/$', views.tier2_cloud_country_view),
    url(r'^tier2/cloud/federation/(?P<federation>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier2_cloud_federation_view),
    url(r'^tier2/cloud/federation/(?P<federation>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.tier2_cloud_federation_view),
    url(r'^tier2/cloud/federation/(?P<federation>[\w-]+)/$', views.tier2_cloud_federation_view),
    url(r'^tier2/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier2_cloud_site_view),
    url(r'^tier2/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.tier2_cloud_site_view),
    url(r'^tier2/cloud/site/(?P<site>[\w-]+)/$', views.tier2_cloud_site_view),
    url(r'^tier2/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier2_view),
    url(r'^tier2/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.tier2_cloud_view),
    url(r'^tier2/cloud/$', views.tier2_cloud_view),

    url(r'^tier1/node/(?P<node>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier1_node_view),
    url(r'^tier1/node/(?P<node>[\w-]+)/$', views.tier1_node_view),
    url(r'^tier1/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier1_site_view),
    url(r'^tier1/site/(?P<site>[\w-]+)/$', views.tier1_site_view),
    url(r'^tier1/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier1_view),
    url(r'^tier1/$', views.tier1_view),
    url(r'^tier2/country/(?P<country>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier2_country_view),
    url(r'^tier2/country/(?P<country>[\w\S-]+)/$', views.tier2_country_view),
    url(r'^tier2/federation/(?P<federation>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier2_federation_view),
    url(r'^tier2/federation/(?P<federation>[\w-]+)/$', views.tier2_federation_view),
    url(r'^tier2/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier2_site_view),
    url(r'^tier2/site/(?P<site>[\w-]+)/$', views.tier2_site_view),
    url(r'^tier2/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.tier2_view),
    url(r'^tier2/$', views.tier2_view),

    url(r'^egi/countries/(?P<query>[\w\s]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.egi_countries_view),
    url(r'^egi/countries/$', views.egi_countries_view),
    url(r'^egi/(?P<query>[\w]+)/$', views.egi_view),
    url(r'^egi/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.egi_view),
    url(r'^egi/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/$', views.egi_view),
    url(r'^egi/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.egi_view),
    url(r'^egi/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.egi_view),
    url(r'^egi/ngi/(?P<ngi>[\w-]+)$', views.egi_ngi_view),
    url(r'^egi/ngi/(?P<ngi>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.egi_ngi_view),
    url(r'^egi/country/(?P<country>[\w\s-]+)$', views.egi_country_view),
    url(r'^egi/country/(?P<country>[\w\s-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.egi_country_view),
    url(r'^egi/$', views.egi_view),

    url(r'^egi/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.egi_site_view),
    url(r'^egi/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/$', views.egi_site_view),
    url(r'^egi/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.egi_site_view),
    url(r'^egi/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.egi_site_view),
    url(r'^egi/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/$', views.egi_site_view),
    url(r'^egi/site/(?P<site>[\w-]+)$', views.egi_site_view),

    url(r'^osg/cloud/(?P<query>[\w]+)/$', views.osg_cloud_view),
    url(r'^osg/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.osg_cloud_view),
    url(r'^osg/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/$', views.osg_cloud_view),
    url(r'^osg/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.osg_cloud_view),
    url(r'^osg/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.osg_cloud_view),
    url(r'^osg/cloud/$', views.osg_cloud_view),

    url(r'^osg/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.osg_cloud_site_view),
    url(r'^osg/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/$', views.osg_cloud_site_view),
    url(r'^osg/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.osg_cloud_site_view),
    url(r'^osg/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.osg_cloud_site_view),
    url(r'^osg/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/$', views.osg_cloud_site_view),
    url(r'^osg/cloud/site/(?P<site>[\w-]+)$', views.osg_cloud_site_view),

    url(r'^osg/(?P<query>[\w]+)/$', views.osg_view),
    url(r'^osg/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.osg_view),
    url(r'^osg/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/$', views.osg_view),
    url(r'^osg/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.osg_view),
    url(r'^osg/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.osg_view),
    url(r'^osg/$', views.osg_view),

    url(r'^osg/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.osg_site_view),
    url(r'^osg/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/$', views.osg_site_view),
    url(r'^osg/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.osg_site_view),
    url(r'^osg/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.osg_site_view),
    url(r'^osg/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/$', views.osg_site_view),
    url(r'^osg/site/(?P<site>[\w-]+)$', views.osg_site_view),


    url(r'^site_admin/cloud/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.site_admin_cloud_view),
    url(r'^site_admin/cloud/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.site_admin_cloud_view),
    url(r'^site_admin/cloud/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.site_admin_cloud_view),
    url(r'^site_admin/cloud/(?P<site>[\w-]+)/(?P<query>[\w]+)/$', views.site_admin_cloud_view),
    url(r'^site_admin/cloud/$', views.site_admin_cloud_view),

    url(r'^site_admin/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.site_admin_view),
    url(r'^site_admin/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.site_admin_view),
    url(r'^site_admin/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.site_admin_view),
    url(r'^site_admin/(?P<site>[\w-]+)/(?P<query>[\w]+)/$', views.site_admin_view),
    url(r'^site_admin/$', views.site_admin_view),

    url(r'^vo_admin/cloud/site/(?P<site>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.vo_admin_cloud_site_view),
    url(r'^vo_admin/cloud/site/(?P<site>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.vo_admin_cloud_site_view),
    url(r'^vo_admin/cloud/site/(?P<site>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.vo_admin_cloud_site_view),
    url(r'^vo_admin/cloud/site/(?P<site>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/$', views.vo_admin_cloud_site_view),
    url(r'^vo_admin/cloud/site/(?P<site>[\w-]+)/(?P<vo>[\w\S-]+)/$', views.vo_admin_cloud_site_view),
    url(r'^vo_admin/cloud/ngi/(?P<ngi>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.vo_admin_cloud_ngi_view),
    url(r'^vo_admin/cloud/ngi/(?P<ngi>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.vo_admin_cloud_ngi_view),
    url(r'^vo_admin/cloud/ngi/(?P<ngi>[\w-]+)/(?P<vo>[\w\S-]+)/$', views.vo_admin_cloud_ngi_view),
    url(r'^vo_admin/cloud/country/(?P<country>[\w\S-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.vo_admin_cloud_country_view),
    url(r'^vo_admin/cloud/country/(?P<country>[\w\S-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.vo_admin_cloud_country_view),
    url(r'^vo_admin/cloud/country/(?P<country>[\w\S-]+)/(?P<vo>[\w\S-]+)/$', views.vo_admin_cloud_country_view),
    url(r'^vo_admin/cloud/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.vo_admin_cloud_view),
    url(r'^vo_admin/cloud/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.vo_admin_cloud_view),
    url(r'^vo_admin/cloud/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.vo_admin_cloud_view),
    url(r'^vo_admin/cloud/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/$', views.vo_admin_cloud_view),
    url(r'^vo_admin/cloud/$', views.vo_admin_cloud_view),
    url(r'^vo_admin/site/(?P<site>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.vo_admin_site_view),
    url(r'^vo_admin/site/(?P<site>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.vo_admin_site_view),
    url(r'^vo_admin/site/(?P<site>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.vo_admin_site_view),
    url(r'^vo_admin/site/(?P<site>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/$', views.vo_admin_site_view),
    url(r'^vo_admin/site/(?P<site>[\w-]+)/(?P<vo>[\w\S-]+)/$', views.vo_admin_site_view),
    url(r'^vo_admin/ngi/(?P<ngi>[\w-]+)/(?P<vo>[\w\S-]+)/$', views.vo_admin_ngi_view),
    url(r'^vo_admin/ngi/(?P<ngi>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.vo_admin_ngi_view),
    url(r'^vo_admin/ngi/(?P<ngi>[\w-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.vo_admin_ngi_view),
    url(r'^vo_admin/country/(?P<country>[\w\S-]+)/(?P<vo>[\w\S-]+)/$', views.vo_admin_country_view),
    url(r'^vo_admin/country/(?P<country>[\w\S-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.vo_admin_country_view),
    url(r'^vo_admin/country/(?P<country>[\w\S-]+)/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.vo_admin_country_view),
    url(r'^vo_admin/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.vo_admin_view),
    url(r'^vo_admin/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.vo_admin_view),
    url(r'^vo_admin/(?P<vo>[\w\S-]+)/(?P<query>[\w]+)/$', views.vo_admin_view),
    url(r'^vo_admin/$', views.vo_admin_view),

    url(r'^user_view/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.user_view_cloud_site_view),
    url(r'^user_view/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.user_view_cloud_site_view),
    url(r'^user_view/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.user_view_cloud_site_view),
    url(r'^user_view/cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/$', views.user_view_cloud_site_view),
    url(r'^user_view/cloud/site/(?P<site>[\w-]+)/$', views.user_view_cloud_site_view),
    url(r'^user_view/cloud/ngi/(?P<ngi>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.user_view_cloud_ngi_view),
    url(r'^user_view/cloud/ngi/(?P<ngi>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.user_view_cloud_ngi_view),
    url(r'^user_view/cloud/ngi/(?P<ngi>[\w-]+)/$', views.user_view_cloud_ngi_view),
    url(r'^user_view/cloud/country/(?P<country>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.user_view_cloud_country_view),
    url(r'^user_view/cloud/country/(?P<country>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.user_view_cloud_country_view),
    url(r'^user_view/cloud/country/(?P<country>[\w\S-]+)/$', views.user_view_cloud_country_view),
    url(r'^user_view/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.user_view_cloud_view),
    url(r'^user_view/cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.user_view_cloud_view),
    url(r'^user_view/cloud/$', views.user_view_cloud_view),
    url(r'^user_view/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.user_view_site_view),
    url(r'^user_view/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.user_view_site_view),
    url(r'^user_view/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.user_view_site_view),
    url(r'^user_view/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/$', views.user_view_site_view),
    url(r'^user_view/site/(?P<site>[\w-]+)/$', views.user_view_site_view),
    url(r'^user_view/ngi/(?P<ngi>[\w-]+)/$', views.user_view_ngi_view),
    url(r'^user_view/ngi/(?P<ngi>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.user_view_ngi_view),
    url(r'^user_view/ngi/(?P<ngi>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.user_view_ngi_view),
    url(r'^user_view/country/(?P<country>[\w\S-]+)/$', views.user_view_country_view),
    url(r'^user_view/country/(?P<country>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.user_view_country_view),
    url(r'^user_view/country/(?P<country>[\w\S-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.user_view_country_view),
    url(r'^user_view/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.user_view_view),
    url(r'^user_view/$', views.user_view_view),
    url(r'^cloud/countries/(?P<query>[\w\s]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.cloud_countries_view),
    url(r'^cloud/countries/$', views.cloud_countries_view),

    url(r'^cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.cloud_view),
    url(r'^cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.cloud_view),
    url(r'^cloud/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.cloud_view),
    url(r'^cloud/(?P<query>[\w]+)/$', views.cloud_view),
    url(r'^cloud/$', views.cloud_view),
    url(r'^cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.cloud_site_view),
    url(r'^cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.cloud_site_view),
    url(r'^cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/$', views.cloud_site_view),
    url(r'^cloud/site/(?P<site>[\w-]+)/(?P<query>[\w]+)/$', views.cloud_site_view),
    url(r'^cloud/site/(?P<site>[\w-]+)$', views.cloud_site_view),
    url(r'^cloud/ngi/(?P<ngi>[\w-]+)$', views.cloud_ngi_view),
    url(r'^cloud/ngi/(?P<ngi>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.cloud_ngi_view),
    url(r'^cloud/ngi/(?P<ngi>[\w-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.cloud_ngi_view),
    url(r'^cloud/country/(?P<country>[\w\s-]+)/$', views.cloud_country_view),
    url(r'^cloud/country/(?P<country>[\w\s-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/$', views.cloud_country_view),
    url(r'^cloud/country/(?P<country>[\w\s-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.cloud_country_view),
    url(r'^wlcg/report/tier1/$', rebus_tier1_views.customised),
    url(r'^wlcg/country/(?P<country>[\w\s-]+)$', views.wlcg_country_view),
    url(r'^wlcg/country/(?P<country>[\w\s-]+)/(?P<query>[\w]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.wlcg_country_view),
    url(r'^wlcg/countries/(?P<query>[\w\s]+)/(?P<yRange>[\w\s]+)/(?P<xRange>[\w\s]+)/(?P<sYear>\d\d\d\d)/(?P<sMonth>\d{1,2})/(?P<eYear>\d\d\d\d)/(?P<eMonth>\d{1,2})/(?P<VOGroup>[\w\S]+)/(?P<localJobGroup>[\w]+)/$', views.wlcg_countries_view),
    url(r'^wlcg/countries/$', views.wlcg_countries_view),
]
